language: julia

os:
  - linux
  - osx

julia:
# - 0.6
  - 0.7
  - 1.0

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --inline=no --check-bounds=yes -e 'VERSION < v"0.7.0-DEV.5183" || using Pkg; Pkg.clone(pwd()); Pkg.build("FlatArrays"); Pkg.test("FlatArrays"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'VERSION < v"0.7.0-DEV.5183" || using Pkg; cd(Pkg.dir("FlatArrays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
  # push coverage results to Codecov
  - julia -e 'VERSION < v"0.7.0-DEV.5183" || using Pkg; cd(Pkg.dir("FlatArrays")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';